### ISSUE TITLE
Migrating from Webpack to Rollup 

### ISSUE THREAD

**Issue by T-Knott-Mesh** [PolymerLabs/lit-element-starter-ts#9]
Hello all, 

Happy to see this Starter Kit coming together. 

If you have an ability to include a dynamic import example that would be awesome.

I have been working on getting treeshaking through rollup to work with dynamic imports, esNext, and WebWorkers -- to say the least, it has proven difficult. 

Cheers, 
-Tsavo

**Comment by justinfagnani** [comment]
Since this starter kit doesn't use a build, outside of the checksize script, I'm not sure what we could do here to help. Bundling is generally going to be a concern of applications, and this is just an element starter kit.

**Comment by T-Knott-Mesh** [comment]
Ahh, no worries - we can close this actually as I ended up getting the config I needed!

Thanks Justin - Hope everyone is doing okay in SF, stay safe!
